require 'rails_helper'

RSpec.describe Direction do
  it 'exists' do
    data = { route: { hasTollRoad: false,
                      hasBridge: false,
                      boundingBox: { lr: { lng: -104.995712, lat: 39.749771 },
                                     ul: { lng: -104.996773, lat: 39.75061 } },
                      distance: 0.081,
                      hasTimedRestriction: false,
                      hasTunnel: false,
                      hasHighway: false,
                      computedWaypoints: [],
                      routeError: { errorCode: -400, message: '' },
                      formattedTime: '00:00:40',
                      sessionId: '6039318f-03cd-6750-02b4-3298-0e702a53e757',
                      hasAccessRestriction: false,
                      realTime: 41,
                      hasSeasonalClosure: false,
                      hasCountryCross: false,
                      fuelUsed: 0.01,
                      legs: [{ hasTollRoad: false,
                               hasBridge: false,
                               destNarrative: '',
                               distance: 0.081,
                               hasTimedRestriction: false,
                               hasTunnel: false,
                               hasHighway: false,
                               index: 0,
                               formattedTime: '00:00:40',
                               origIndex: -1,
                               hasAccessRestriction: false,
                               hasSeasonalClosure: false,
                               hasCountryCross: false,
                               roadGradeStrategy: [[]],
                               destIndex: -1,
                               time: 40,
                               hasUnpaved: false,
                               origNarrative: '',
                               maneuvers: [{ distance: 0.081,
                                             streets: ['17th St'],
                                             narrative: 'Start out going southeast on 17th St toward Larimer St/CO-33.',
                                             turnType: 6,
                                             startPoint: { lng: -104.996773, lat: 39.75061 },
                                             index: 0,
                                             formattedTime: '00:00:40',
                                             directionName: 'Southeast',
                                             maneuverNotes: [],
                                             linkIds: [],
                                             signs: [],
                                             mapUrl: 'http://www.mapquestapi.com/staticmap/v5/map?key=J7awB9ajQGoAakRx4aFEfeeGr4Vb0bo3&size=225,160&locations=39.7506103515625,-104.99677276611328|marker-1||39.74977111816406,-104.99571228027344|marker-2||&center=39.75019073486328,-104.99624252319336&defaultMarker=none&zoom=14&rand=-1609070771&session=6039318f-03cd-6750-02b4-3298-0e702a53e757',
                                             transportMode: 'AUTO',
                                             attributes: 0,
                                             time: 40,
                                             iconUrl: 'http://content.mqcdn.com/mqsite/turnsigns/icon-dirs-start_sm.gif',
                                             direction: 5 },
                                           { distance: 0,
                                             streets: [],
                                             narrative: '1225 17TH ST is on the right.',
                                             turnType: -1,
                                             startPoint: { lng: -104.995712, lat: 39.749771 },
                                             index: 1,
                                             formattedTime: '00:00:00',
                                             directionName: '',
                                             maneuverNotes: [],
                                             linkIds: [],
                                             signs: [],
                                             transportMode: 'AUTO',
                                             attributes: 0,
                                             time: 0,
                                             iconUrl: 'http://content.mqcdn.com/mqsite/turnsigns/icon-dirs-end_sm.gif',
                                             direction: 0 }],
                               hasFerry: false }],
                      options: { arteryWeights: [],
                                 cyclingRoadFactor: 1,
                                 timeType: 0,
                                 useTraffic: false,
                                 returnLinkDirections: false,
                                 countryBoundaryDisplay: true,
                                 enhancedNarrative: false,
                                 locale: 'en_US',
                                 tryAvoidLinkIds: [],
                                 drivingStyle: 2,
                                 doReverseGeocode: true,
                                 generalize: -1,
                                 mustAvoidLinkIds: [],
                                 sideOfStreetDisplay: true,
                                 routeType: 'FASTEST',
                                 avoidTimedConditions: false,
                                 routeNumber: 0,
                                 shapeFormat: 'raw',
                                 maxWalkingDistance: -1,
                                 destinationManeuverDisplay: true,
                                 transferPenalty: -1,
                                 narrativeType: 'text',
                                 walkingSpeed: -1,
                                 urbanAvoidFactor: -1,
                                 stateBoundaryDisplay: true,
                                 unit: 'M',
                                 highwayEfficiency: 22,
                                 maxLinkId: 0,
                                 maneuverPenalty: -1,
                                 avoidTripIds: [],
                                 filterZoneFactor: -1,
                                 manmaps: 'true' },
                      locations: [{ dragPoint: false,
                                    displayLatLng: { lng: -104.996773, lat: 39.750614 },
                                    adminArea4: 'Denver',
                                    adminArea5: 'Denver',
                                    postalCode: '80202-1507',
                                    adminArea1: 'US',
                                    adminArea3: 'CO',
                                    type: 's',
                                    sideOfStreet: 'R',
                                    geocodeQualityCode: 'P1AAA',
                                    adminArea4Type: 'County',
                                    linkId: 11_848_097,
                                    street: '1331 17th St',
                                    adminArea5Type: 'City',
                                    geocodeQuality: 'POINT',
                                    adminArea1Type: 'Country',
                                    adminArea3Type: 'State',
                                    latLng: { lng: -104.996775, lat: 39.750614 } },
                                  { dragPoint: false,
                                    displayLatLng: { lng: -104.995712, lat: 39.749771 },
                                    adminArea4: 'Denver',
                                    adminArea5: 'Denver',
                                    postalCode: '80202-1501',
                                    adminArea1: 'US',
                                    adminArea3: 'CO',
                                    type: 's',
                                    sideOfStreet: 'L',
                                    geocodeQualityCode: 'P1AAA',
                                    adminArea4Type: 'County',
                                    linkId: 66_312_058,
                                    street: '1225 17th St',
                                    adminArea5Type: 'City',
                                    geocodeQuality: 'POINT',
                                    adminArea1Type: 'Country',
                                    adminArea3Type: 'State',
                                    latLng: { lng: -104.995712, lat: 39.749772 } }],
                      time: 40,
                      hasUnpaved: false,
                      locationSequence: [0, 1],
                      hasFerry: false },
             info: { statuscode: 0,
                     copyright: { imageAltText: '© 2021 MapQuest, Inc.', imageUrl: 'http://api.mqcdn.com/res/mqlogo.gif',
                                  text: '© 2021 MapQuest, Inc.' },
                     messages: [] } }
    search = Direction.new(data)
    expect(search).to be_a Direction
    expect(search).to have_attributes(distance: 0.1,
                                      travel_time: '00:00:40',
                                      steps: ['Start out going southeast on 17th St toward Larimer St/CO-33.',
                                              '1225 17TH ST is on the right.'])
  end
end
