require 'rails_helper'

RSpec.describe Station do
  it 'exists' do
    data = { latitude: 39.750614,
             longitude: -104.996775,
             location_country: 'US',
             precision: { value: 9, name: 'premise', types: ['premise'] },
             station_locator_url: 'https://afdc.energy.gov/stations/',
             total_results: 198,
             station_counts: { total: 447,
                               fuels: { BD: { total: 0 },
                                        E85: { total: 2 },
                                        ELEC: { total: 439, stations: { total: 190 } },
                                        HY: { total: 0 },
                                        LNG: { total: 0 },
                                        CNG: { total: 1 },
                                        LPG: { total: 5 } } },
             offset: 0,
             fuel_stations: [{ access_code: 'public',
                               access_days_time: 'MO: Not Specified; TU: Not Specified; WE: Not Specified; TH: Not Specified; FR: Not Specified; SA: Not Specified; SU: Not Specified',
                               access_detail_code: nil,
                               cards_accepted: nil,
                               date_last_confirmed: '2021-02-26',
                               expected_date: nil,
                               fuel_type_code: 'ELEC',
                               groups_with_access_code: 'Public',
                               id: 147_967,
                               open_date: nil,
                               owner_type_code: nil,
                               status_code: 'E',
                               station_name: 'Seventeenth Street Plaza',
                               station_phone: '800-663-5633',
                               updated_at: '2021-02-26T00:13:15Z',
                               facility_type: nil,
                               geocode_status: 'GPS',
                               latitude: 39.7501605,
                               longitude: -104.9951224,
                               city: 'Denver',
                               intersection_directions: nil,
                               plus4: nil,
                               state: 'CO',
                               street_address: '1225 17th St.',
                               zip: '80202',
                               country: 'US',
                               bd_blends: nil,
                               cng_dispenser_num: nil,
                               cng_fill_type_code: nil,
                               cng_psi: nil,
                               cng_renewable_source: nil,
                               cng_total_compression: nil,
                               cng_total_storage: nil,
                               cng_vehicle_class: nil,
                               e85_blender_pump: nil,
                               e85_other_ethanol_blends: nil,
                               ev_connector_types: ['J1772'],
                               ev_dc_fast_num: nil,
                               ev_level1_evse_num: nil,
                               ev_level2_evse_num: 2,
                               ev_network: 'SemaCharge Network',
                               ev_network_web: 'https://semaconnect.com/',
                               ev_other_evse: nil,
                               ev_pricing: '$1.00-$6.00/Hr Variable Parking Fee',
                               ev_renewable_source: nil,
                               hy_is_retail: nil,
                               hy_pressures: nil,
                               hy_standards: nil,
                               hy_status_link: nil,
                               lng_renewable_source: nil,
                               lng_vehicle_class: nil,
                               lpg_primary: nil,
                               lpg_nozzle_types: nil,
                               ng_fill_type_code: nil,
                               ng_psi: nil,
                               ng_vehicle_class: nil,
                               access_days_time_fr: nil,
                               intersection_directions_fr: nil,
                               bd_blends_fr: nil,
                               groups_with_access_code_fr: 'Public',
                               ev_pricing_fr: nil,
                               ev_network_ids: { station: ['1114'], posts: %w[2642 2643] },
                               distance: 0.0934,
                               distance_km: 0.15031 },
                             { access_code: 'public',
                               access_days_time: '24 hours daily',
                               access_detail_code: nil,
                               cards_accepted: nil,
                               date_last_confirmed: '2021-02-26',
                               expected_date: nil,
                               fuel_type_code: 'ELEC',
                               groups_with_access_code: 'Public',
                               id: 161_489,
                               open_date: nil,
                               owner_type_code: nil,
                               status_code: 'E',
                               station_name: '16M BUILDING 16M B-1',
                               station_phone: '888-758-4389',
                               updated_at: '2021-02-26T00:21:41Z',
                               facility_type: nil,
                               geocode_status: 'GPS',
                               latitude: 39.749408,
                               longitude: -104.998468,
                               city: 'Denver',
                               intersection_directions: nil,
                               plus4: nil,
                               state: 'CO',
                               street_address: '1550 Market St',
                               zip: '80202',
                               country: 'US',
                               bd_blends: nil,
                               cng_dispenser_num: nil,
                               cng_fill_type_code: nil,
                               cng_psi: nil,
                               cng_renewable_source: nil,
                               cng_total_compression: nil,
                               cng_total_storage: nil,
                               cng_vehicle_class: nil,
                               e85_blender_pump: nil,
                               e85_other_ethanol_blends: nil,
                               ev_connector_types: ['J1772'],
                               ev_dc_fast_num: nil,
                               ev_level1_evse_num: nil,
                               ev_level2_evse_num: 2,
                               ev_network: 'ChargePoint Network',
                               ev_network_web: 'http://www.chargepoint.com/',
                               ev_other_evse: nil,
                               ev_pricing: nil,
                               ev_renewable_source: nil,
                               hy_is_retail: nil,
                               hy_pressures: nil,
                               hy_standards: nil,
                               hy_status_link: nil,
                               lng_renewable_source: nil,
                               lng_vehicle_class: nil,
                               lpg_primary: nil,
                               lpg_nozzle_types: nil,
                               ng_fill_type_code: nil,
                               ng_psi: nil,
                               ng_vehicle_class: nil,
                               access_days_time_fr: nil,
                               intersection_directions_fr: nil,
                               bd_blends_fr: nil,
                               groups_with_access_code_fr: 'Public',
                               ev_pricing_fr: nil,
                               ev_network_ids: { station: ['USCPIL100365'], posts: %w[117059 117061] },
                               distance: 0.12268,
                               distance_km: 0.19743 },
                             { access_code: 'public',
                               access_days_time: '24 hours daily',
                               access_detail_code: nil,
                               cards_accepted: nil,
                               date_last_confirmed: '2021-02-26',
                               expected_date: nil,
                               fuel_type_code: 'ELEC',
                               groups_with_access_code: 'Public',
                               id: 89_045,
                               open_date: nil,
                               owner_type_code: nil,
                               status_code: 'E',
                               station_name: 'TABOR GARAGE HORACE',
                               station_phone: '888-758-4389',
                               updated_at: '2021-02-26T00:21:41Z',
                               facility_type: nil,
                               geocode_status: 'GPS',
                               latitude: 39.748823,
                               longitude: -104.996585,
                               city: 'Denver',
                               intersection_directions: nil,
                               plus4: nil,
                               state: 'CO',
                               street_address: '1201-1299 16th St',
                               zip: '80202',
                               country: 'US',
                               bd_blends: nil,
                               cng_dispenser_num: nil,
                               cng_fill_type_code: nil,
                               cng_psi: nil,
                               cng_renewable_source: nil,
                               cng_total_compression: nil,
                               cng_total_storage: nil,
                               cng_vehicle_class: nil,
                               e85_blender_pump: nil,
                               e85_other_ethanol_blends: nil,
                               ev_connector_types: ['J1772'],
                               ev_dc_fast_num: nil,
                               ev_level1_evse_num: nil,
                               ev_level2_evse_num: 2,
                               ev_network: 'ChargePoint Network',
                               ev_network_web: 'http://www.chargepoint.com/',
                               ev_other_evse: nil,
                               ev_pricing: nil,
                               ev_renewable_source: nil,
                               hy_is_retail: nil,
                               hy_pressures: nil,
                               hy_standards: nil,
                               hy_status_link: nil,
                               lng_renewable_source: nil,
                               lng_vehicle_class: nil,
                               lpg_primary: nil,
                               lpg_nozzle_types: nil,
                               ng_fill_type_code: nil,
                               ng_psi: nil,
                               ng_vehicle_class: nil,
                               access_days_time_fr: nil,
                               intersection_directions_fr: nil,
                               bd_blends_fr: nil,
                               groups_with_access_code_fr: 'Public',
                               ev_pricing_fr: nil,
                               ev_network_ids: { station: ['USCPIL254891'], posts: %w[1991481 1991491] },
                               distance: 0.12398,
                               distance_km: 0.19953 },
                             { access_code: 'public',
                               access_days_time: '24 hours daily',
                               access_detail_code: nil,
                               cards_accepted: nil,
                               date_last_confirmed: '2021-02-26',
                               expected_date: nil,
                               fuel_type_code: 'ELEC',
                               groups_with_access_code: 'Public',
                               id: 89_046,
                               open_date: nil,
                               owner_type_code: nil,
                               status_code: 'E',
                               station_name: 'TABOR GARAGE AUGUSTA',
                               station_phone: '888-758-4389',
                               updated_at: '2021-02-26T00:21:41Z',
                               facility_type: nil,
                               geocode_status: 'GPS',
                               latitude: 39.748815,
                               longitude: -104.996618,
                               city: 'Denver',
                               intersection_directions: nil,
                               plus4: nil,
                               state: 'CO',
                               street_address: '1200 17th St',
                               zip: '80202',
                               country: 'US',
                               bd_blends: nil,
                               cng_dispenser_num: nil,
                               cng_fill_type_code: nil,
                               cng_psi: nil,
                               cng_renewable_source: nil,
                               cng_total_compression: nil,
                               cng_total_storage: nil,
                               cng_vehicle_class: nil,
                               e85_blender_pump: nil,
                               e85_other_ethanol_blends: nil,
                               ev_connector_types: ['J1772'],
                               ev_dc_fast_num: nil,
                               ev_level1_evse_num: nil,
                               ev_level2_evse_num: 2,
                               ev_network: 'ChargePoint Network',
                               ev_network_web: 'http://www.chargepoint.com/',
                               ev_other_evse: nil,
                               ev_pricing: nil,
                               ev_renewable_source: nil,
                               hy_is_retail: nil,
                               hy_pressures: nil,
                               hy_standards: nil,
                               hy_status_link: nil,
                               lng_renewable_source: nil,
                               lng_vehicle_class: nil,
                               lpg_primary: nil,
                               lpg_nozzle_types: nil,
                               ng_fill_type_code: nil,
                               ng_psi: nil,
                               ng_vehicle_class: nil,
                               access_days_time_fr: nil,
                               intersection_directions_fr: nil,
                               bd_blends_fr: nil,
                               groups_with_access_code_fr: 'Public',
                               ev_pricing_fr: nil,
                               ev_network_ids: { station: ['USCPIL247171'], posts: %w[2129351 2129361] },
                               distance: 0.1244,
                               distance_km: 0.2002 },
                             { access_code: 'public',
                               access_days_time: 'MO: 06:00am-06:00pm; TU: 06:00am-06:00pm; WE: 06:00am-06:00pm; TH: 06:00am-06:00pm; FR: 06:00am-06:00pm; SA: Closed; SU: Closed',
                               access_detail_code: nil,
                               cards_accepted: nil,
                               date_last_confirmed: '2021-02-26',
                               expected_date: nil,
                               fuel_type_code: 'ELEC',
                               groups_with_access_code: 'Public',
                               id: 147_964,
                               open_date: nil,
                               owner_type_code: nil,
                               status_code: 'E',
                               station_name: '1800 Larimer',
                               station_phone: '800-663-5633',
                               updated_at: '2021-02-26T00:13:15Z',
                               facility_type: nil,
                               geocode_status: 'GPS',
                               latitude: 39.7512822,
                               longitude: -104.9944365,
                               city: 'Denver',
                               intersection_directions: nil,
                               plus4: nil,
                               state: 'CO',
                               street_address: '1800 Larimer Street, Suite 1800',
                               zip: '80202',
                               country: 'US',
                               bd_blends: nil,
                               cng_dispenser_num: nil,
                               cng_fill_type_code: nil,
                               cng_psi: nil,
                               cng_renewable_source: nil,
                               cng_total_compression: nil,
                               cng_total_storage: nil,
                               cng_vehicle_class: nil,
                               e85_blender_pump: nil,
                               e85_other_ethanol_blends: nil,
                               ev_connector_types: ['J1772'],
                               ev_dc_fast_num: nil,
                               ev_level1_evse_num: nil,
                               ev_level2_evse_num: 2,
                               ev_network: 'SemaCharge Network',
                               ev_network_web: 'https://semaconnect.com/',
                               ev_other_evse: nil,
                               ev_pricing: '$0.00-$8.00/Hr Variable Parking Fee, $0.13/kWh Energy Fee',
                               ev_renewable_source: nil,
                               hy_is_retail: nil,
                               hy_pressures: nil,
                               hy_standards: nil,
                               hy_status_link: nil,
                               lng_renewable_source: nil,
                               lng_vehicle_class: nil,
                               lpg_primary: nil,
                               lpg_nozzle_types: nil,
                               ng_fill_type_code: nil,
                               ng_psi: nil,
                               ng_vehicle_class: nil,
                               access_days_time_fr: nil,
                               intersection_directions_fr: nil,
                               bd_blends_fr: nil,
                               groups_with_access_code_fr: 'Public',
                               ev_pricing_fr: nil,
                               ev_network_ids: { station: ['1036'], posts: %w[2391 2392] },
                               distance: 0.13279,
                               distance_km: 0.2137 }] }
    search = Station.new(data)
    expect(search).to be_a Station
    expect(search).to have_attributes(name: 'Seventeenth Street Plaza',
                                      address: '1225 17th St. Denver CO 80202',
                                      fuel_type: 'ELEC',
                                      access_times: 'MO: Not Specified; TU: Not Specified; WE: Not Specified; TH: Not Specified; FR: Not Specified; SA: Not Specified; SU: Not Specified')
  end
end
